# Generated by Django 2.2.16 on 2020-10-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diamond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField()),
                ('length', models.FloatField()),
                ('angle', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rectangle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField()),
                ('length', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Square',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Triangle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side_a', models.FloatField()),
                ('side_b', models.FloatField()),
                ('side_c', models.FloatField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='triangle',
            constraint=models.CheckConstraint(check=models.Q(side_a__gt=0), name='side_a_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='triangle',
            constraint=models.CheckConstraint(check=models.Q(side_b__gt=0), name='side_b_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='triangle',
            constraint=models.CheckConstraint(check=models.Q(side_c__gt=0), name='side_c_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='square',
            constraint=models.CheckConstraint(check=models.Q(length__gt=0), name='length_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='rectangle',
            constraint=models.CheckConstraint(check=models.Q(length__gt=0), name='length_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='rectangle',
            constraint=models.CheckConstraint(check=models.Q(width__gt=0), name='width_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='diamond',
            constraint=models.CheckConstraint(check=models.Q(length__gt=0), name='length_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='diamond',
            constraint=models.CheckConstraint(check=models.Q(width__gt=0), name='width_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='diamond',
            constraint=models.CheckConstraint(check=models.Q(angle__gt=0), name='angle_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='diamond',
            constraint=models.CheckConstraint(check=models.Q(angle__lt=180), name='angle_lt_180'),
        ),
    ]
