# Generated by Django 2.2.16 on 2020-10-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='triangle',
            name='side_a_gt_0',
        ),
        migrations.RemoveConstraint(
            model_name='triangle',
            name='side_b_gt_0',
        ),
        migrations.RemoveConstraint(
            model_name='triangle',
            name='side_c_gt_0',
        ),
        migrations.RenameField(
            model_name='triangle',
            old_name='side_a',
            new_name='base',
        ),
        migrations.RenameField(
            model_name='triangle',
            old_name='side_b',
            new_name='height',
        ),
        migrations.RemoveField(
            model_name='triangle',
            name='side_c',
        ),
        migrations.AddConstraint(
            model_name='triangle',
            constraint=models.CheckConstraint(check=models.Q(base__gt=0), name='base_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='triangle',
            constraint=models.CheckConstraint(check=models.Q(height__gt=0), name='height_gt_0'),
        ),
    ]
